sudo: required
services:
  - docker

before install:
  - docker build -t travis/dock -f Dockerfile .

script:
  - docker run -e CI=true travis/dock npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "travis-test"
  env: "TravisTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-517503597657"
  bucket_path: "travis-test"
  on:
	branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key: $ACCESS_SECRET

