version: '3'
services:
  web:
    build: .
    ports: 
      - "8000:3000"
    volumes:
      - /apps/node_modules
      - .:/apps
  tests:
    build: .
    volumes:
      - /apps/node_modules
      - .:/apps
    command: ["npm", "run", "test"]